
- name: module stat et register
  hosts: 192.168.216.132
  become: true
  tasks:
  - name: create directory
    file:
      path: /tmp/ussf/{{ item.dir }}/{{ item.file }}
      state: directory
    with_items:
    - { dir: "dir1", file: "file1.txt" }
    - { dir: "dir2", file: "file2.txt" }
    - { dir: "dir3", file: "file3.txt" }
