

- name: file playbook
  hosts: 192.168.216.132
  become: true
  tasks:
  - name: check connexion
    ping:

  - name: create directory
    file:
      path: "/tmp/test/1/2/3/4"
      state: directory
      owner: root
      group: root
      mode: 0755
