

- name: file playbook
  hosts: 192.168.216.132
  become: true
  tasks:
  - name: check connexion
    ping:

  - name: create symb link
    file:
      src: "/tmp/test/1/2/3/4/"
      dest: "/tmp/symlink"
      state: link
      owner: root
      group: root
      mode: 0755
