- name: my playbook
  hosts: all
  become: yes
  vars:
    files:
    - { source: "file1.txt" , destination: "/home/youssef", mode: "0755", owner: "youssef"}
    - { source: "file2.txt" , destination: "/home/youssef", mode: "0644", owner: "youssef"}

  tasks:

  - name: module copy
    copy:
      src: "{{ item.source }}"
      dest: "{{ item.destination }}"
      mode: "{{ item.mode }}"
      owner: "{{ item.owner }}"
    with_items:
    - "{{ files }}"

